### ISSUE TITLE
Some textures/bump maps extracted from a BNTX are corrupt

### ISSUE THREAD

**Issue by gayfrogog** [aboood40091/BNTX-Extractor#1]
Some textures/bump maps extracted from a BNTX are corrupt, thus cannot be converted to other formats. 

I'll include a BNTX and sample DDS extracted from it in a .zip.
[CorruptDDS.zip](https://github.com/aboood40091/BNTX-Extractor/files/1847104/CorruptDDS.zip)

**Comment by aboood40091** [comment]
They convert correctly for me...
[CorruptDDS2.zip](https://github.com/aboood40091/BNTX-Extractor/files/1851493/CorruptDDS2.zip)
